name: CI - Build & Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Gera build (valida TypeScript)
      - name: Build
        run: npm run build

      # 5️⃣ Executa testes com coverage
      - name: Run tests with coverage
        env:
          NODE_ENV: TEST
          JWT_SECRET: githubci
        run: npm run test:coverage

      # 6️⃣ (opcional) Salva relatório de cobertura como artefato
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/